/**
 * @class PR.util.Messages
 * 
 * Auxiliar para definir el titulos,labes,columnas,botones,dialogos
 * 
 * @version 1.1
 */

Ext.ClassManager.create('PR.util.Messages', {
	singleton: true,
	alternateClassName: ['Messages'],

	//Valores de los combos fijos
	combos:{
		abril:'Abril',
		activo:'Activo',
		agosto:'Agosto',
		aprobado:'Aprobado',
		diciembre:'Diciembre',
		elaborado:'Elaborado',
		enero:'Enero',
		febrero:'Febrero',
		inactivo:'Inactivo',
		julio:'Julio',
		junio:'Junio',
		marzo:'Marzo',
		mayo:'Mayo',
		noviembre:'Noviembre',
		octubre:'Octubre',
		preaprobado:'Pre-aprobado',
		rechazado:'Rechazado',
		revisado:'Revisado',
		septiembre:'Septiembre',
		solicitado:'Solicitado'
	},
	
	//Etiquetas de formularios
	labels: {
		abril: 'Abril',
		activo:'Activo',
		agosto: 'Agosto',
		area:'Área',
		antecedente: 'Antecedente',
		beneficiarioHombre: 'Hombres',
		beneficiarioMujer: 'Mujeres',
		beneficiarioTotal: 'Total',
		cambiarContrasenha:'Cambiar Contraseña',
		cantidadBeneficiario: 'Cantidad',
		cicloRecurso: 'Ciclo del Recurso',
		clasificacion: 'Clasificación',
		confirmarContrasenha:'Confirmar Contraseña',
		contrasenha:'Contraseña',
		contrasenhaAnterior:'Contraseña anterior',
		correoElectronico:'Correo Electrónico',
//		dependencia: 'Grupo de Unidad' /*'Ente de Gobierno'*/,
		dependencia: 'Dependencia',
		descripcion: 'Descripción',
		diciembre: 'Diciembre',
		ejecucion: 'Modalidad de Ejecución',
		ejercicio: 'Ejercicio',
		empleosEventuales: 'Empleos Eventuales',
		empleosPermanentes: 'Empleos Permanentes',
		enero: 'Enero',
		estatus:'Estatus',
		febrero: 'Febrero',
		fechaFinal: 'Fecha Final',
		fechaInicial: 'Fecha Inicial',	
		finals:'Final',
		fuenteFinanciamiento: 'Fuente de Financiamiento',
		funcion: 'Función',
		grupoUnidad:'Grupo Unidad',
		inicial:'Inicial',
		inicio:'Inicio',
		inversionAnterior: 'Inversión Anterior',
		inversionPendiente: 'Inversión Pendiente',
		inversionProgramada: 'Inversión Programada',
		inversionTotal: 'Inversión Total',		
		impactoSocial: 'Impacto Social y Productivo',
		julio: 'Julio',	
		junio: 'Junio',
		justificacion: 'Justificación',
		lineaAccion: 'Línea de Acción',	
		localidad: 'Localidad',
		marzo: 'Marzo',		
		mayo: 'Mayo',
		mecanicaOperativa: 'Mecánica Operativa',
		metasAnteriores: 'Metas Anteriores',
		metasProgramadas: 'Metas Programadas',
		metasPendientes: 'Metas Pendientes',
		metasTotales: 'Metas Totales',
		modalidadEjecicion: 'Modalidad de Ejecución',
		modificar:'Modificar',
		municipio: 'Municipio',		
		nombre:'Nombre',
		nombreEmpleado:'Nombre de Empleado',
		nombreProyecto: 'Nombre del Proyecto',	
		nombreUsuario:'Nombre de Usuario',
		noviembre: 'Noviembre',	
		nuevaContrasenha:'Nueva Contraseña',
		numProyecto: 'Proyecto',	
		objetivo: 'Objetivo',
		octubre: 'Octubre',
		oficioRespuesta:'Oficio de Respuesta',
		oficioSolicitud: 'Oficio de Solicitud',	
		oficio:'Oficio',
		partidas:'Partidas',
		participacion: 'Participación',	
		periodo:'periodo',
		prioridad: 'Prioridad',
		procedencia: 'Procedencia',
		programa: 'Programa',
		programaEspecial: 'Programa Especial',
		proyecto:'Proyecto',
		proyectoComplementario: 'Proyecto Complementario',
		puesto:'Puesto',
		rol:'Rol',
		roles:'Roles',	
		sector: 'Sector',
		septiembre: 'Septiembre',				
		subfuncion: 'Sub Función',
		subprograma: 'Sub Programa',
		subsector: 'Sub Sector',		
		tipoBeneficiario: 'Descripción',				
		tipoProyecto: 'Tipo de Proyecto',
		total:'Total',
		unidadAdministrativa:'Unidad Administrativa',
		unidades:'Unidades',
		unidadMedida: 'Unidad de Medida',
		usuario:'Usuario',
		vencimiento:'Vencimiento'
	},

	//Titulos de los paneles
	titles: {
		archivos: 'Archivos',
		archivosGrid: 'Archivos Agregados',
		areas:'Áreas',
		beneficiarios: 'Beneficiarios',
		beneficiariosGrid: 'Beneficiarios Agregados',
		detalleDisponiblePeriodo:'Detalle Disponible al Periodo',
		disponibleAcumuladoPeriodo:'Disponible Acumulado por Periodo',
		empleados:'Empleados',
		lineasAccion: 'Líneas de Acción',
		metasPorcentuales: 'Calendario de Metas Porcentuales',	
		oficioSolicitudGrid:function(value){
			return 'Oficio de Solicitud: '+value;
		},
		proyectos:'Proyectos',		
		puesto:'Puesto',
		rangoFechasSolicitud:'Rango de Fechas de Solicitud',
		roles:'Roles',
		unidades:'Unidades',
		usuarios:'Usuarios'
	},

	//Encabezados de columnas de los grid
	columns: {
		abril:'Abril',
		acciones:'Acciones',
		activo:'Activo',
		acumulado:'Acumulado',
		agosto:'Agosto',
		ampliacion:'Ampliacion',
		aprobado:'Aprobado',
		area:'Área',
		autorizado:'Autorizado',
		cantidad:'Cantidad',
		codigo:'Código',
		codigoGrupo:'Código Grupo',	
		codigoUnidad:'Código Unidad',
		comprometido:'Comprometido',
		contabilizado:'Contabilizado',
		correoElectronico:'Correo Electrónico',
		cuentas:'Cuentas',
		disponible:'Disponible',
		dependencia:'Dependencia',
		descripcion:'Descripción',	
		detalle:'Detalle',
		diciembre:'Diciembre',
		ejercido:'Ejercido',
		eliminar:'Eliminar',
		enero:'Enero',
		estatus:'Estatus',		
		febrero:'Febrero',
		fechaSolicitud:'Fecha de Solicitud',
		julio:'Julio',
		junio:'Junio',
		inicio:'Inicio',
		marzo:'Marzo',
		mayo:'Mayo',
		mr:'Ministraciones',
		mrRemanente:'MrRemanente',
		modificado:'Modificado',
		nombre:'Nombre',
		nombreUnidad:'Nombre Unidad',	
		noviembre:'Noviembre',
		octubre:'Octubre',
		oficioSolicitud:'Oficio de Solicitud',
		oficioRespuesta:'Oficio de Respuesta',		
		partida:'Partida',
		periodo:'Periodo',
		pReduccion:'Reduccion Pendiente',
		proyecto:'Proyecto',
		puesto:'Puesto',
		reduccion:'Reduccion',
		rol:'Rol',
		roles:'Roles',
		septiembre:'Septiembre',
		unidad:'Unidad',
		url:'Url',
		usuario:'Usuario',		
		vencimiento:'Vencimiento'
	},

	//Etiquetas de botones
	btn: {
		aceptar:'Aceptar',
		actualizarEstatus:'Actualizar Estatus',
		agregarArchivo: 'Agregar Archivo',
		agregarBeneficiario: 'Agregar Beneficiarios',
		agregarLineaAccion: 'Agregar Línea de Acción',
		agregarProyectoUsuario:'Agregar Proyectos al Usuario',
		agregarPuesto:'Agregar Puesto',
		agregarRol:'Agregar Rol',
		agregarUnidad:'Agregar Unidad',
		agregarUnidadesUsuarios:'Agregar Unidades al Usuario',
		agregarUsuario:'Agregar Usuario',
		aprobarSolicitud:'Aprobar Solicitud',
		buscar:'Buscar',
		cambiarContrasenha:'Cambiar contraseña ',
		cancelar:'Cancelar',
		cargarArchivo: 'Cargar Archivo',
		eliminarProyectosUsuarios: 'Eliminar Proyectos al Usuario',
		eliminarUnidadesUsuarios:'Eliminar Unidades al Usuario',		
		guardarBorrador: 'Guardar Borrador de Cédula Básica',
		guardar:'Guardar',			
		limpiar:'Limpiar',	
		modificarFechasOficios:'Modificar Fechas de Oficios',
		modificarPuesto:'Modificar Puesto',
		rechazarSolicitud:'Rechazar Solicitud',
		regresarSolicitudElaborado:'Regresar Solicitud a Elaborado',
		regresar:'Regresar',
		seleccionarArchivo: 'Seleccione el Archivo'
	},

	//Dialogos
	dialogs: {
		titles: {
			accionNoPermitida:'¡Acción no Permitida!',
			advertencia:'Advertencia',
			area:'Área',
			areas:'Áreas',
			aviso:'Aviso',
			confirmar: 'Por favor, confirme esta acción',
			empleados:'Empleados',
			error: '¡Error!',
			errorOperacion:'¡Error en la Operación!',
			esperePorFavor:'Espere Por Favor',		
			noPermitido: 'Acción no Permitida',			
			operacionExitosa:'Operación Exitosa',
			puesto:'Puesto',
			reduccionesPendiente:'Reducciones Pendientes',
			success: '¡Acción Finalizada con Éxito!',
			modificarArea:'Modificar Área'
		},
		body: {
			actualizarModificacionesEliminaraSeleccion:	'Se actualizarán  todas las partidas modificadas y se eliminaran las que se encuentren seleccionadas ¿Está seguro que desea continuar?',
			actualizacionExitosaProyecto:				'El Proyecto se actualizo de forma exitos',
			agregandoArea:								'Agregando Área',
			areaEliminadaConExito:						'El area se elimino con exito',
			areaRegistradaExito:						'El área se ha registrado con exito, desea agregrar mas áreas',
			areamodificadaExito:						'El área se ha modificado con exito, desea agregrar mas áreas',
			busquedaNoRealizable:						'No se puede realizar la búsqueda',
			busquedaNoexitosa:							'Búsqueda no exitosa',
			capturarUnaPartidaAprobar:					'Debe capturar cuando menos una partida para poder enviar a aprobación',
			cargandoArchivo: 							'Cargando archivo, porfavor espere un momento',
			codigoUtilizadoAnteriormente:				'Existir un código activo con el mismo código en el mismo ejercicio',
			datosProcesaronExito:						'Los datos se procesaron con exito',
			deseaEliminarRol:							'¿Desea Eliminar el Rol?',
			deseaEliminarArea:							'¿Desea eliminar el área?',
			deseaEliminarSiguienteSolicitud:function(value){
											return		'Se eliminara el siguiente oficio "'+value+'" con todas sus partidas ¿Desea continuar?';
			},
			deseaEnviarSolicitudAprobacion:				'¿Desea enviar ahora la solicitud de aprobación? No le será permitido editar sus partidas una vez enviada',
			eliminandoDatos:							'Eliminando Datos...',
			eliminaranDatosSeleccionados:				'Se eliminaran los datos seleccionados de forma permanente, ¿Desea continuar?',
			empleadoRegistradoExito:					'El empleado se ha registrado con exito, desea agregrar mas empleados',
			enviando:									'Enviando...',
			errorServidor: 								'Ocurrió un error inesperado en el servidor mientras se procesaba su solicitud, por favor contacte al administrador del sistema',
			estaSeguroBorrarInformacionPartida:			'¿Está seguro que desea borrar la información de esta partida?',
			existenMovimientosSinGuardar:				'Existen movimientos presupuestales sin guardar, es necesario que los guarde antes de enviar la solicitud',
			existeUnMovimientoFueraDelPeriodo:			'El oficio de solicitud tiene movimientos fuera del periodo presupuestal',
			formularioError: 							'Existen errores en el formulario',
			guardando:									'Guardando...',
			guardeCambiosAntesEliminar:					'Guarde los cambios de las partidas antes de eliminar una partida',
			guardeCambiosAntesEliminarPartidas:			'Guarde los cambios de las partidas antes de eliminar un grupo de partidas',
			inversionMuyGrande:							'La inversión programada es una cantidad muy grande, por favor recalcule su planeación',
			losDatosSeEliminaran:						'El registro se eliminara de forma permanente, ¿Desea continuar?',
			moviminetosNosePuedenAprobar:				'Los movimientos no se pueden aprobar hasta que se apruebe el proyecto',
			noExisteDatosTabla:							'No existe datos en la Tabla',
			noExistenMovimientosQueGuardar:				'No existen movimientos que guardar',
			noEncontraronDatos:							'No se encontraron datos',
			noPuedeRealizarBusqueda:					'No se puede realizar la búsqueda',
			nosePuedeEliminarGrupo:function(value){
											return 	 	'Nose pueden eliminar el grupo de solicitud porque el proyecto <b>'+value+'</b> tiene cuentas activas';
			},
			noseEncuentranDatosEnviar:					'No se encuentran datos para enviar',
			noTienePermisoSuficientes:					'Este usuario solo tiene permisos para consultar, necesita más privilegios para continuar',
			oficioRespuestaUtilizado:function(value){
											return 		'Este oficio "'+value+'" de respuesta ya fue utilizado anteriormente ¿Deseas continuar? ';
			},
			oficioSolicitudExisteEnOtroEstatus:			'El oficio existe en otro estatus distinto de elaborado',
			oficioSolicitudCambiaElaborado:				'Los oficios seleccionados pasaran a estatus de elaborado, ¿Desea continuar?',
			validacionReduccionOficio:function(proyecto,partida,mes){
											return 		'Esta intentando aprobar una reduccion en el proyecto <b>"'+proyecto+'"</b> en la partida <b>"'+partida+'"</b> en el periodo de <b>"'+mes+'"</b> y no tiene el disponible necesario';},
			validacionReduccionOficioMovimiento:function(proyecto,partida,mes,oficio){
											return 		'Esta intentando aprobar un movimiento o proyecto con el oficio <b>"'+oficio+'"</b> el cual tiene una reduccion en el proyecto <b>"'+proyecto+'"</b> en la partida <b>"'+partida+'"</b> en el periodo de <b>"'+mes+'"</b> y no tiene el disponible necesario';},
			procesandoDatos:							'Procesando Datos...',
			proyectoNosePuedeElimonarCuentasActivas:	'El proyecto no se puede eliminar porque tiene cuentas activas',
			proyectoPendienteAprobar:function(oficioSolicitud,proyecto,oficioProyecto){
											return  	'No se pueden aprobar movimientos con el oficio de solicitud <b>"'+oficioSolicitud+'"</b> porque el proyecto <b>"'+proyecto+'"</b> tiene un oficio de solicitud <b>"'+oficioProyecto+'"</b> no aprobado';
			},
			seEliminaronDatosExito:						'Se eliminaron los datos con exito',
			seEnviaraElOficio:function(value){
											return 		'Se enviara el siguiente oficio "'+value+'" ¿Desea continuar?';
			},
			seleccionUnaMasfilas:						'Seleccione una o mas filas en la tabla',
			seleccioneUnaPartidaEliminar:				'Seleccione una partida ha eliminar',
			solicitudAprobacionEnviadaExito:			'La solicitud de aprobación del proyecto ha sido enviada correctamente'
		}
	},

	//Tooltips
	tooltips: {
		eliminar: 'Eliminar',
		detalle:'Detalle',
		imprimir:'Imprimir'
	},
	
	//PagingToolbar
	pagingtoolbar:{
		displayMsg:'Mostrando {0} a {1} de {2} elementos',
		emptyMsg: 'No hay elementos para mostrar',
		beforePageText: 'Página',
		afterPageText: 'de {0}'
	},
	
	//Errores de validación
	errors: {
		markInvalid:{
			esteCampoObligatorio:'Este campo es obligatorio'},
		maxLength:{
			excedeCaracteres:'Excede el número máximo de caracteres permitidos'
			},
		proyectoComplementario: 'Ingrese solamente proyectos complementarios con letras mayúsculas y/o números, separados por comas'
	}
});