
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package mx.gob.tabasco.saf.siafe.ws.servicios.impl;

import java.util.logging.Logger;
//import javax.jws.WebMethod;
//import javax.jws.WebParam;
//import javax.jws.WebResult;
//import javax.jws.WebService;
//import javax.xml.bind.annotation.XmlSeeAlso;
//import javax.xml.ws.RequestWrapper;
//import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-04-13T13:59:37.404-05:00
 * Generated source version: 2.5.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "ControlConsecutivosServicioService",
                      portName = "ControlConsecutivosServicioPort",
                      targetNamespace = "http://impl.servicios.ws.siafe.saf.tabasco.gob.mx/",
//                      wsdlLocation = "http://192.168.15.221:8080/pruebas/ws/services/ControlConsecutivosServicioPort?wsdl",
                      endpointInterface = "mx.gob.tabasco.saf.siafe.ws.servicios.impl.ControlConsecutivoServicoSEI")
                      
public class ControlConsecutivoServicoSEIImpl implements ControlConsecutivoServicoSEI {

    private static final Logger LOG = Logger.getLogger(ControlConsecutivoServicoSEIImpl.class.getName());

    /* (non-Javadoc)
     * @see mx.gob.tabasco.saf.siafe.ws.servicios.impl.ControlConsecutivoServicoSEI#obtieneID(java.lang.String  arg0 )*
     */
    public java.lang.Long obtieneID(java.lang.String arg0) { 
        LOG.info("Executing operation obtieneID");
        System.out.println(arg0);
        try {
            java.lang.Long _return = Long.valueOf(-1991395543352632950l);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see mx.gob.tabasco.saf.siafe.ws.servicios.impl.ControlConsecutivoServicoSEI#obtieneCVE(java.lang.String  arg0 )*
     */
    public java.lang.Long obtieneCVE(java.lang.String arg0) { 
        LOG.info("Executing operation obtieneCVE");
        System.out.println(arg0);
        try {
            java.lang.Long _return = Long.valueOf(-4315282180609905515l);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
