package mx.gob.tabasco.saf.siafe.ws.servicios.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

import mx.gob.tabasco.saf.siafe.presupuesto.utilerias.ConfiguracionWSUtil;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-04-13T13:59:37.464-05:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "ControlConsecutivosServicioService", 
//                  wsdlLocation = "http://192.168.15.221:8080/pruebas/ws/services/ControlConsecutivosServicioPort?wsdl",
                  targetNamespace = "http://impl.servicios.ws.siafe.saf.tabasco.gob.mx/") 
public class ControlConsecutivosServicioService extends Service {

    public final static URL WSDL_LOCATION;
    
    public static String URL = ConfiguracionWSUtil.getProperties().getProperty("ws.consecutivos.url");

    public final static QName SERVICE = new QName("http://impl.servicios.ws.siafe.saf.tabasco.gob.mx/", "ControlConsecutivosServicioService");
    public final static QName ControlConsecutivosServicioPort = new QName("http://impl.servicios.ws.siafe.saf.tabasco.gob.mx/", "ControlConsecutivosServicioPort");
    static {
        URL url = null;
        try {
        	  url = new URL(URL);
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ControlConsecutivosServicioService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.15.221:8080/pruebas/ws/services/ControlConsecutivosServicioPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ControlConsecutivosServicioService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ControlConsecutivosServicioService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ControlConsecutivosServicioService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ControlConsecutivoServicoSEI
     */
    @WebEndpoint(name = "ControlConsecutivosServicioPort")
    public ControlConsecutivoServicoSEI getControlConsecutivosServicioPort() {
        return super.getPort(ControlConsecutivosServicioPort, ControlConsecutivoServicoSEI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ControlConsecutivoServicoSEI
     */
    @WebEndpoint(name = "ControlConsecutivosServicioPort")
    public ControlConsecutivoServicoSEI getControlConsecutivosServicioPort(WebServiceFeature... features) {
        return super.getPort(ControlConsecutivosServicioPort, ControlConsecutivoServicoSEI.class, features);
    }

}
